# Ch17 | 19/24 | Step 4: Add the Logo and Save the Changes [script]
# Automate 1e by Al Sweigart (CC-BY-NC-SA) - https://automatetheboringstuff.com/1e/chapter17

Resizing zophie.png...
Adding logo to zophie.png...
