# Ch16 | 28/36 | Step 3: Send Customized Email Reminders [script]
# Automate 1e by Al Sweigart (CC-BY-NC-SA) - https://automatetheboringstuff.com/1e/chapter16

Sending email to alice@example.com...
Sending email to bob@example.com...
Sending email to eve@example.com...
